# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PYCOGROUP_TINDER' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RealmSwift'
  # Pods for PYCOGROUP_TINDER

  target 'PYCOGROUP_TINDERTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PYCOGROUP_TINDERUITests' do
    # Pods for testing
  end

end
